#!/usr/bin/env python3
# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4
##
# mPlane Software Development Kit
# Component runtime
#
# (c) 2015 mPlane Consortium (http://www.ict-mplane.eu)
#     Author: Stefano Pentassuglia <stefano.pentassuglia@ssbprogetti.it>
#             Brian Trammell <brian@trammell.ch>
#
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.
#

import mplane.component
import mplane.utils
import json
import sys
import argparse

if __name__ == "__main__":

    global args
    parser = argparse.ArgumentParser(description='mplane component runtime')
    parser.add_argument('--config', metavar='conf-file', default="component.json",
                        help='Configuration file for the component')
    args = parser.parse_args()

    # Try to read the configuration file
    config = mplane.utils.get_config(args.config)

    if "Listener" in config["Component"]:
        component = mplane.component.ListenerHttpComponent(config)
        if "Initiator" in config["Component"]: 
            print("Ignoring 'Initiator' section in configuration file")
    elif "Initiator" in config["Component"]:
        component = mplane.component.InitiatorHttpComponent(config)
    else:
        print("Need either a 'Initiator' or 'Listener' under 'Component' in " + args.config)

